### ISSUE TITLE
Custom handlers

### ISSUE THREAD

**Issue by jefersonkaefer** [k911/swoole-bundle#210]
Hello,

**Very nice package.**

Is possible rewrite the handlers to my customs handlers? 
I need add somethings to request and response, but I don't know how.
Thanks!

**Comment by k911** [comment]
Hello @jefersonkaefer when using this package as a Symfony Bundle you can use Symfony's DI Container to override services (look: https://github.com/k911/swoole-bundle/blob/develop/src/Bridge/Symfony/Bundle/Resources/config/services.yaml, here: https://github.com/k911/swoole-bundle/blob/develop/src/Bridge/Symfony/Bundle/DependencyInjection/SwooleExtension.php)

You can also use `bin/console debug:container` commands
