### ISSUE TITLE
AdvancedStaticFileServer should fallback to mime type text/plain on when serving unknown file extension

### ISSUE THREAD

**Issue by Rastusik** [k911/swoole-bundle#238]
**Is your feature request related to a problem? Please describe.**
Current behaviour with AdvancedStaticFileServer doesn't serve requested static file when the requested file has an extension unknown to the AdvancedStaticFileServer, but proxies the request to the symfony kernel.

**Describe the solution you'd like**
I suggest to treat file extensions unknown to the AdvancedStaticFileServer configuration by default as text/plain, so the requested file would be served to the client, even though with the wrong mime type.
Alternatively I suggest to make the AdvancedStaticFileServer mime types configurable using symfony config mechanism, to be able to add custom mime types (e.g. sqlite, which I need to serve in my project).

**Comment by k911** [comment]
> Alternatively I suggest to make the AdvancedStaticFileServer mime types configurable using symfony config mechanism, to be able to add custom mime types (e.g. sqlite, which I need to serve in my project).

Definitely I would love that.

> I suggest to treat file extensions unknown to the AdvancedStaticFileServer configuration by default as text/plain, so the requested file would be served to the client, even though with the wrong mime type.

Maybe `application/octet-stream` as AWS does?

**Comment by Rastusik** [comment]
> Maybe application/octet-stream as AWS S3 does?

ok, no problem
