### ISSUE TITLE
Profiler toolbar doesn't collect logs

### ISSUE THREAD

**Issue by Rastusik** [k911/swoole-bundle#241]
**Describe the bug**
Symfony profiler (debug toolbar) doesn't collect logs with symfony-swoole

**Steps To Reproduce**
Enable the profiler toolbar and try to log something during a profiled request. When going to the request profile from the toolbar, the Logs menu item doesn't contain any data.

**Expected behavior**
There should be data in the logs menu item.

**Comment by k911** [comment]
Can you explain further why do you think it is a `swoole-bundle` bug?

Also, please try using 1 worker or enabling session storage, my guess is that it relies on that. If not please provide at least some logs and a minimal reproducible example.

**Comment by Rastusik** [comment]
It is a Symfony bug, I already have a fix for this, I'm just playing with it a little more. This bug doesn't have anything to do with session storage.

**Comment by Rastusik** [comment]
```
/**
 * This is an override for Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddDebugLogProcessorPass
 * which removes debug processor from loggers when Symfony is run from CLI.
 * Without debug log processor, there are no logs being shown in the symfony profiler. This override
 * replaces the original configurator for 'monolog.logger_prototype' with a custom one, which removes
 * the debug log processor only when being run from PHPDBG.
 */
```
