### ISSUE TITLE
Your work is a millennium job LOL

### ISSUE THREAD

**Issue by CoderChang65535** [k911/swoole-bundle#280]
@k911 

So excited to hear that this project is selected by Github Archive Program.

**Comment by k911** [comment]
Thanks @CoderChang65535 

Anyway: https://archiveprogram.github.com/faq/

> What public repositories are archived in the Arctic Code Vault?
> On February 2, 2020 we took a snapshot of all of GitHub’s public repositories that have been active within recent months. The archive will include every repo with any commits between the announcement at GitHub Universe on November 13, 2019 and February 2, 2020, every repo with at least 1 star and any commits from the year before the snapshot (02/02/2019 - 02/02/2020), and every repo with at least 250 stars. Plus, gh-pages for any repository that meets the aforementioned criteria.

**Comment by CoderChang65535** [comment]
@k911 In fact I also get the ```Arctic Code Vault Contributor``` badge from your project since I only change a little lines.....
