### ISSUE TITLE
Unable to upgrade to v0.8.3 on PHP 8.0 due to assertion BC break

### ISSUE THREAD

**Issue by spyridonas** [k911/swoole-bundle#441]
**Is your feature request related to a problem? Please describe.**
Installation of this package does not work with php 8
(beberlei/assert[v3.0.0, ..., v3.2.7] require php ^7 -> your php version (8.0.1) does not satisfy that requirement.)

**Describe the solution you'd like**
Merge https://github.com/k911/swoole-bundle/pull/417

**Comment by k911** [comment]
For now you can use workaround:

```
```

**Comment by spyridonas** [comment]
Thanks for the reply, i will try using your suggestion.
After reading the beberlei/assert issue and searching around, there's a suggestion to use https://github.com/webmozart/assert instead.
Maybe that's the solution ? I don't know if you've consider/tested if before.

**Comment by k911** [comment]
@spyridonas I'm satisfied with how the current assertion library works. It may be wise to actually remove this dependency completely and use exceptions and checks crafted directly for this bundle. However, it would take a significant amount of time to rewrite and properly test it, so I think it is probably easier to fix the assertion library instead, as PR https://github.com/beberlei/assert/pull/310 exists which should handle that.

**Comment by k911** [comment]
I'm closing this one as fix in dependency has been released
