### ISSUE TITLE
Is that a good idea to make the default host from 'localhost' to '0.0.0.0'?

### ISSUE THREAD

**Issue by CoderChang65535** [k911/swoole-bundle#54]
I think using '0.0.0.0' as default value can be much better than 'localhost' because it contains '127.0.0.1' or 'localhost' and is easy to expose without any configuration.

**Comment by k911** [comment]
Yes, @CoderChang65535 it think this is reasonable setting. Would you like to prepare a pull request, then?

**Comment by CoderChang65535** [comment]
Thanks and I'm glad to do that. I will do it later.

**Comment by CoderChang65535** [comment]
Hi, @k911 .
I'm not sure what commit message I should set as the style as the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular)?
Could you give some help for that?
Is that the one you like:
`feat(config): set default host value to '0.0.0.0'`

**Comment by k911** [comment]
It's more like `fix` I think, because using `localhost` as default means `0.0.0.0` does not work and users might expect to work this out of the box in e.g. docker container.
