### ISSUE TITLE
header already sent exception when session_start

### ISSUE THREAD

**Issue by sunchuo** [k911/swoole-bundle#65]
When running under swoole, header_sent() always returns true and headers_list() returns null.
Session start throws an exception. It has nothing to do with the session storage driver， native\pdo both have this problem.

**Comment by k911** [comment]
Yes, this behaviour is correct, I believe. Symfony does not handle sessions with swoole correctly yet. Could you please try solution mentioned in #6?

**Comment by sunchuo** [comment]
> Yes, this behaviour is correct, I believe. Symfony does not handle sessions with swoole correctly yet. Could you please try solution mentioned in #6?


problem solved! thanks!!
