### ISSUE TITLE
RE - How to fix error handling? 

### ISSUE THREAD

**Issue by domgraziano** [k911/swoole-bundle#78]
**Describe the bug**
Linked to #20 
From any symfony controller if an error or exception is thrown, the symfony request response cycle does not terminate and the browser (or any client eg postman) is hanging waiting for the response which never comes back. 

**Steps To Reproduce**
I'm adding a repository with a symfony installation wrapped in a docker container to reproduce you would have 3 endpoint
- localhost:9501/success  ok
- localhost:9501/error throwing error 
- localhost:9501/exception throwing exception

here the repo:
[trySwoole.zip](https://github.com/k911/swoole-bundle/files/3827220/trySwoole.zip)

**Expected behavior**
Response finishes with 500 code / server error

**Environment (please complete the following information):**
Dockerised varsion started from https://www.swoole.co.uk/article/docker.html but substituted with php php:7.3-cli as the bundle requires 7.3 and swoole-4.4.7  

**Logs**

```

Fatal error: Uncaught Swoole\ExitException: swoole exit in /app/project/vendor/symfony/debug/ErrorHandler.php:668
Stack trace:
#0 [internal function]: Symfony\Component\Debug\ErrorHandler::Symfony\Component\Debug\{closure}()
#1 {main}
  thrown in /app/project/vendor/symfony/debug/ErrorHandler.php on line 668

```

**Comment by Rastusik** [comment]
@k911  I'm experiencing this too btw

**Comment by k911** [comment]
@domgraziano @Rastusik To confirm, you didn't install `twig` and configure symfony's expcetion handler  (as described here https://symfony.com/doc/current/controller/error_pages.html) or don't want to, correct?

**Comment by Rastusik** [comment]
@k911 I have twig bundle installed. Exceptions are handled fine, if they are caught by Symfony, but the described problem occurs to me on php errors

**Comment by k911** [comment]
@Rastusik 

>  if they are caught by Symfony

So your case is probably different than @domgraziano , because I see than @domgraziano don't have `twig` pack installed. 

@domgraziano 

Installing `twig` should fix your problems, just run:

```
composer require twig
```

**Comment by domgraziano** [comment]
@k911 thanks for looking into it. 

I can confirm that installing twig would terminate the request but only for thrown Exception, not for error (in my example, with twig, running in prod mode, the localhost:9501/error would still hang and response never come back).

My view is that I shouldn't be forced to install twig though. As per after symfony 4 I could have only a few components to being able to speed up a minimal API for which I might or might not need twig at all, which was my original case. 

I do agree that the server itself should be able to terminate the request, and the bundle should probably provide such a mechanism. If you have any idea on where to look, I can have a look myself. I tried to catch a `\Swoole\ExitException` in the `K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler` without success

**Comment by domgraziano** [comment]
@k911 actually I've just tried: 
```
    public function handle(SwooleRequest $request, SwooleResponse $response): void
    {
	try {
	     $httpFoundationRequest = $this->requestFactory->make($request);
	     $httpFoundationResponse = $this->kernel->handle($httpFoundationRequest);	
	     $this->responseProcessor->process($httpFoundationResponse, $response);		
	} catch(\Error $e) {
	        return;
	} catch(\Exception $e) {
	        return;
	}
		
        if ($this->kernel instanceof TerminableInterface) {
            $this->kernel->terminate($httpFoundationRequest, $httpFoundationResponse);
        }
    }
``` 
in `K911\Swoole\Bridge\Symfony\HttpKernel\HttpKernelRequestHandler`

and this would terminate with a 500, without Twig, downside is that nothing will be logged as we are returning, so it might not be that immediate as a fix
